### ISSUE TITLE
Hi~ How long will release a stable version?

### ISSUE THREAD

**Issue by ghost** [naveenshaji/material#1]
Dear Naveen, 
I really appreciate your awesome stuff about this jekyll theme.
I'm an android developer without any web skill. 
Do you have any useful advises when using your theme?
Thx in advance anyway!

**Comment by naveenshaji** [comment]
Hi John,
A stable version of material is expected to be released in a month or two. We have planned to release material in three different variants - as a Jekyll theme, as a HTML5 template, and one bundled with a 'one-click' CMS. As an android developer, you should be able to use the HTML5 version as a front-end for your apps.

Regards,

**Comment by ghost** [comment]
Thx for the idea~
Your suggestion is really to the point. But i want use it as my blog's theme! :)
I'm very grateful that you answer my question!
Looking forward to the released version.

**Comment by naveenshaji** [comment]
Hi John,
Using material as your blog theme with Jekyll and GitHub pages can be easily done. Upon release, we will provide a better detailed walk-through on how you can proceed to do this. If you happen to own a server as well, then you may even use the version bundled with the CMS. Likewise instructions for this will also be available upon release. This CMS-based method will be the easiest to get a blog up and running without getting too technical at all, and will be virtually 'one-click'.

Regards,

**Comment by ghost** [comment]
Ty very much!!! :+1: 
Best regards~
