### ISSUE TITLE
questions on blog and posts

### ISSUE THREAD

**Issue by alexolivet** [naveenshaji/material#6]
Hello Naveen,

I am playing around with your design a bit. i have followed all your steps and it worked quite easily. I am new to GitHub. I was wondering if you would an explanation on how to post and attached an image to it. I have read and read over again but I am not sure where to 'markdown' a post? I am sorry, I hope I am clear.
Thanks,
elwebman.nl

**Comment by naveenshaji** [comment]
Hello,

Material follows the standard Jekyll Posts structure. You can take a look [here](http://jekyllrb.com/docs/posts/) to see how you can add posts with images and other resources. Take a look and let me know if you need more help.
Regards,
Naveen Shaji.

**Comment by alexolivet** [comment]
Thank you Naveen.this is very much appreciated. Alex

elwebman.nl
